
##########################################################################################
#
# Secrets & Configs
#
##########################################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.instance_name }}-db-creds
  namespace: {{ .Values.namespace }}
  annotations:
    secret-generator.v1.mittwald.de/encoding: hex
    secret-generator.v1.mittwald.de/autogenerate: database_password,database_username,jwt
type: Opaque
data: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.instance_name }}-app-secret
  namespace: {{ .Values.namespace }}
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: app_secret
type: Opaque
data: {}
---
##########################################################################################
#
# Volumes
#  on ne crée que les claims, le volumes seront provisionnés automatiquement par k8s
##########################################################################################

# api-uploads volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.instance_name }}-api-uploads
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# database volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.instance_name }}-postgres-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
