apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.instance_name }}-api
  namespace: {{ .Values.namespace }}
spec:
  loadBalancerIP:
  ports:
    - protocol: TCP
      name: web
      port: 3000
  selector:
    app: {{ .Values.instance_name }}-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.instance_name }}-frontoffice
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      name: web-frontoffice
      port: 80
  selector:
    app: {{ .Values.instance_name }}-frontoffice