# cors header
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.instance_name }}-corsheader
  namespace: {{ .Values.namespace }}
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
      - "PATCH"
      - "DELETE"
      - "POST"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList:
      - "https://{{ .Values.base_url }}"
      - "https://api.{{ .Values.base_url }}"
      - "*"
    accessControlMaxAge: 100
    addVaryHeader: true
    accessControlAllowCredentials: true
