---
apiVersion: traefik.io/v1alpha1
kind: "IngressRoute"
metadata:
  name: {{ .Values.instance_name }}
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    ############################################
    # frontend
    ############################################
    - kind: "Rule"
      match: Host(`{{ .Values.base_url }}`)
      services:
        - name: {{ .Values.instance_name }}-frontoffice
          port: 80
    ############################################
    # API
    ############################################
    - kind: "Rule"
      match: Host(`api.{{ .Values.base_url }}`)
      services:
        - name: {{ .Values.instance_name }}-api
          port: 3000
  tls:
    certResolver: letsencrypt